services:
  db_watersystem:
    image: postgis/postgis:15-3.3
    container_name: postgis_watersystem
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_watersystem
      - POSTGRES_DB=watersystem

    ports:
      - "5436:5432"

    volumes:
      - ./pgdata_watersystem:/var/lib/postgresql/data
      - ../../db/schema:/docker-entrypoint-initdb.d

    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
